HELP = 'YANDEX.HELP'
WHAT_CAN_YOU_DO = 'YANDEX.WHAT_CAN_YOU_DO'

USER_STUDY_GROUP = 'user_study_group'

SCHEDULE_COUNT = 'schedule_count'
SCHEDULE_LIST = 'schedule_list'

SCHEDULE_INTENTS = [
    SCHEDULE_COUNT,
    SCHEDULE_LIST
]
