HELP = 'YANDEX.HELP'
WHAT_CAN_YOU_DO = 'YANDEX.WHAT_CAN_YOU_DO'

CONFIRM = 'YANDEX.CONFIRM'
REJECT = 'YANDEX.REJECT'

USER_STUDY_GROUP_SET = 'user_study_group_set'
USER_STUDY_GROUP_UPDATE = 'user_study_group_update'

USER_STUDY_GROUP_INTENTS = [
    CONFIRM,
    REJECT,
    USER_STUDY_GROUP_SET,
    USER_STUDY_GROUP_UPDATE
]

SCHEDULE_COUNT = 'schedule_count'
SCHEDULE_LIST = 'schedule_list'

SCHEDULE_INTENTS = [
    SCHEDULE_COUNT,
    SCHEDULE_LIST
]

EXIT = 'exit_skill'

EXIT_INTENTS = [
    EXIT
]